#!/bin/sh
# Wrapper to execute sch-scripts as root.
# Copyright (C) 2012 Alkis Georgopoulos <alkisg@gmail.com>
# License GNU GPL version 3 or newer <http://gnu.org/licenses/gpl.html>

run_as_root() {
    if [ -x /usr/bin/kdesudo ]; then
        exec kdesudo -- "$@"
    elif [ -x /usr/bin/gksudo ]; then
        exec gksudo -- "$@"
    else
        if [ -x /usr/bin/sudo ]; then
            set sudo -- "$@"
        elif [ -x /bin/su ]; then
            set su -c "$*"
        fi
        if [ -t 0 ]; then
            exec "$@"
        elif [ -x run-in-terminal ]; then
            exec ./run-in-terminal "$@"
        else
            echo "Could not find gksudo or kdesudo in order to run: $*" >&2
            exit 1
        fi
    fi
}

if [ -x /usr/share/sch-scripts/sch-scripts.py ]; then
    cd /usr/share/sch-scripts
    case "$1" in
        # help and version need to run without root
        -h|--help|-v|--verson) ./sch-scripts.py "$@" ;;
        *) run_as_root ./sch-scripts.py "$@" ;;
    esac
else
    echo "/usr/share/sch-scripts/sch-scripts.py not found" >&2
    exit 1
fi
