#!/bin/sh
# Start tuxtype with the correct theme for the current locale.

prog=${0##*/}
if [ ! -x "/usr/games/$prog" ]; then
    echo "$prog: command not found" >&2
    exit 127
fi

for f in /usr/share/tuxtype/themes/*/settings.txt; do
    while IFS="=" read var value; do
        test "$var" = "theme_locale_name" && break
    done <"$f"
    if [ "$var" = "theme_locale_name" ] && [ "$value" = "$LANG" ]; then
        theme_name=${f%/settings.txt}
        theme_name=${theme_name##*/}
        exec "/usr/games/$prog" --theme "$theme_name"
    fi
done
exec "/usr/games/$prog"
