# These paths are configured by the install script.
python = "@PYTHON@/"
version = "@VERSION@/"
localedir = "@localedir@/"
datadir = "@datadir@/"
pkgdatadir = "@pkgdatadir@/"
bindir = "@bindir@/"
sbindir = "@sbindir@/"
scriptsdir = "@scriptsdir@/"
sysconfdir = "@sysconfdir@/"
