#!/bin/sh
# Restart gnome-panel if it fails to load (LP: #1078679).

prog=${0##*/}
if [ ! -x "/usr/bin/$prog" ]; then
    echo "$prog: command not found" >&2
    exit 127
fi

if [ "$LTSP_FATCLIENT" != "True" ]; then
    exec "/usr/bin/$prog" "$@"
fi

"/usr/bin/$prog" "$@" &
sleep 15
if ! pgrep -nx indicator-sound -U $USER >/dev/null 2>&1; then
    echo "$(date) - restarting $prog" >> $HOME/.xsession-errors
    exec "/usr/bin/$prog" --replace
fi
