#!/bin/sh
# Copyright (C) 2012 Alkis Georgopoulos <alkisg@gmail.com>
# License GNU GPL version 3 or newer <http://gnu.org/licenses/gpl.html>

usage() {
    cat <<EOF
Usage: $0 [OPTIONS] [COMMAND]

It runs the specified COMMAND in a terminal, either the current if one
is open, or in a new one if run e.g. with Alt+F2.
In the end it shows a failure or success message.

As a special case, if run as /tmp/sch-scripts with no parameters, it adds
the appropriate repositories and installs sch-scripts.

Options:
    -s, --source  COMMAND is assumed to be a shell script which is sourced in
                  order for it to have access to some common shell functions.
EOF
}

bold() {
    if [ -z "$printbold_first_time" ]; then
        printbold_first_time=true
        bold_face=$(tput bold 2>/dev/null) || true
        normal_face=$(tput sgr0 2>/dev/null) || true
    fi
    echo "${bold_face}$@${normal_face}"
}

log() {
    logger -t sch-scripts -p syslog.err "$@"
}

# Outputs a message to stderr and aborts execution
die() {
    log "$@"
    bold "ERROR in ${0##*/}:" >&2
    echo "$@" >&2
    pause_exit 1
}

# Also contains the greek letters for Yes/No
is_true() {
    case "$1" in
        [YyΝν]|[Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
            return 0
        ;;
        *)
            return 1
        ;;
    esac
}

confirm() {
    local answer

    read -p "$1" answer
    test -n "$answer" || answer="true"
    if ! is_true "$answer"; then
        echo "Ακυρώθηκε από το χρήστη." >&2
        pause_exit 2
    fi
}

pause_exit() {
    local dummy

    if [ "$SPAWNED_TERM" = true ]; then
        read -p "Πατήστε [Enter] για να κλείσετε το παρόν παράθυρο." dummy
    fi
    exit "$@"
}

add_repository()
{
    local repo key lines filename
    repo="$1"

    release="${release:-$(lsb_release -sc)}"
    # Transform linuxmint names to respective ubuntu names
    if [ -f "/usr/share/mintsources/$release/mintsources.conf" ]; then
        release=$(sed -n 's/^base_codename=//p' "/usr/share/mintsources/$release/mintsources.conf")
    fi

    # To get the repository parameters:
    # apt-key list
    # apt-key export 03AFA832
    case "$repo" in
        "ts.sch.gr"|"ts.sch.gr/ppa"|"ts.sch.gr/proposed")
            if [ "$repo" = "ts.sch.gr" ]
            then
                repo="ts.sch.gr/ppa"
            fi
            # Key id: 03AFA832
            key='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mI0ESh2aVQEEALM30nllN7ZvEY7lfOTYoamJWl3axh5h0g4xZB7AXKop1/7zq3uf
uGITGBZuY+YTnn3WhUp76aQzgAkfsMfqyeIrPZVDpY+YMLng2WN4Q9NkziR0gfmI
vOZk157/ug20KRSAmyQnmmKKs1O3qc1ATxJPVvu/OojS6E6DKdHALMhPABEBAAG0
EkxhdW5jaHBhZCBUZXN0IFBQQYifBDABAgAJBQJKLLIAAh0gAAoJEDxyYHsDr6gy
b98EAJU7qCuq7znpT1dbNOYwbjPqBry6MOzhMXIl6RnFGQkgTPi2pLQbJq0U/v46
uGbqPx0o8qFTC/Tg8RRJPH6Xqe7kl7gkfpA/cCCSIEQtnrd8EzOYHGMrt+1FtMsZ
0rfyqQL8Ix7K566dpgEVdfouQJSGIUFZzcd8TsDSrlCHlHM9iLYEEwECACAFAkod
mlUCGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRA8cmB7A6+oMvSKA/9zDRHJ
gInCDBhcmgPBqgDc1Fvcf9z2bcNnL26Af3E8/629vDG2YRU1XtNc9WnYpUgZpDPH
LWbD/zoZuXgKwE1yjPQLJMS153zAG0bsmAaWegHEyQNag7KvWIplyq/I0mac9Q+Z
NmAAta8KJ2tQahnqv4/k7Mlm5jurdoX0fEhPBbRDzpHPgM6/zrjOtc+Ezq7Pgc65
zr8gzqTOtc+Hzr3Ouc66zq7PgiDOo8+Ezq7Pgc65zr7Ot8+CIM6jzpXOoM6VzpfO
pYi2BBMBAgAgBQJKLLHeAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AACgkQPHJg
ewOvqDJUBwQAi0TayFknNG4oP7RFS27ktB4O12uB4ePqwkfwr2bWW6sAlUvObvKV
b2tjo9LumXWjssFmhYQlf4XlMab/GZno/hwIihH21bl4D/qCOmIvAEbim5rwOYHl
lggdYwVk8U8LiO9Ime8BxgehvRle69qr4KLuSln29jYCscD2PLGbGsqIuQQTAQIA
IwIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheABQJKLLNkAhkBAAoJEDxyYHsDr6gy
yM8D/jvaXRV0iOlU5c6kbUKMHzmEWM59QYO+dgzSaDmx77svICb2dcrY+onYpNOB
0ZHmcwlyc4hUw/b7l5t9emRns7lUgw/BBaDnk3vsqWQIyeIcuXZV5JAtwCVBZsE7
NPBKU1xbjWICQVXVB3ZEkIi2Y6tHzVx5hX1GqiRxVfZXo4N/
=buPk
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        "ts.sch.gr-repo"|"ts.sch.gr/repo")
            repo="ts.sch.gr/repo"
            lines="deb http://ts.sch.gr/repo stable main non-free"
            # Key id: 9849BE20
            key='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEodH04RBAC8Gnx7SOytmQCLkvelxjCMOLxDSaaJiGaq3bJBTUJlBaAf3cqb
SBW4bfp9DQkgKHcnsIrGC+zUxYEzZrc6ZvEz+i+v1iMHo+QpJWAJLZ7CF8SRfvTb
w/zysKxSkn59CRfM2gZuoSfVXYKWw9v7kmriKZ7P5ybbssunq76reaWb4wCgmflB
h/vgoQCj5Z5Deu6HQwEn+0sD/0xZvqYGtzHXDEAz2BBXJtORkyS5R6y8KRqgAcQ/
wDtV1xnG52/gOZH6maauqKVpH5S66EFgxr+Rl0IEOCQFbHLUtGZl4dPI/kFD6AcI
JPGKQXgiIwP9yrYJbTnl9tLIPo3Dgv0cfmj4gg/aibjwWPtNTJYckOPSQyVnUEg6
rAJgBAC8AgS2vsau3xPPqRXybdHKqc0+xjZx2NW6xVYGF825UHdx1yaZjgHcw9G1
YfqVoS1eOScXrC6T+BC84fYYT8/a4dS7X2Rk74FYKwcmJ/QW+8a56f1b6K1DcSy8
godpz3e1LkyIL6/58k7qM5M7dJ+lms9wirmq30lkYkWnWbD/QrRlSGVsbGVuaWMg
U2Nob29scyBUZWNobmljYWwgU3VwcG9ydCBUZWFtICjOpM61z4fOvc65zrrOriDO
o8+Ezq7Pgc65zr7OtyDOo86VzqDOlc6XzqUpIDxkZXZzQHRzLnNjaC5ncj6IYAQT
EQIAIAUCSh0fTgIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEEl1LNCYSb4g
058AniBnHSKSZk22AaHmBthl9mwZaXP9AJ4yTfMDHC/itOv0hJLUIDnGnndwxbkC
DQRKHR9OEAgA7CtHQByegpJpRJunBSvqu8xtz/buXVhWBiPpYNBqQF5S4OGXngru
zKlcgzYt5sK8ve4022ba5NfKUEOgQiTSP3p/9w9JYxrL30IeeHKPwL3NLeS3DNV8
wxVJB4CXYHmOQ9B0RM4nBj3wOFEv1UiPMC7kox+E9bi9lQJXVmECqKrtadvwaoqU
ncvhMb/Etg3Kstrsi7MkPtCalbgCi/acvDSKF1Wf6EKFla7eywY6U2heFASUpMg4
2FqA4DyL/avg5zvdDg6cuk05P4Zudq/e80hyvVWA6LPWM5FEJnPlz31vWKMKtrRH
pUEFFBiOzb2FQg9zyRlkF8qjPCEkKnC+twAECwgAmiVlyqSpl7K+y2/yZB4dWCjE
AyHJRUK8AVL0KGPgTo+YWnBImq+7eOw0hVMVbMWrwv2r0s/l7SsBI723KsMVvurY
A2/kqj8+UM24t40YDAr8qAeP4UACtWlRy9PAUQQ1+4ygPYnRK81RBXLL2WYF25GL
Qj+4zvUz4bqkQTv91fjjwpX03YaoVaBKngNjPOgOlQtZM0E5k7C98pESOb4AHoju
y2tMEfhoa2cf7KdywmN0EjYHaL+3VIb6mTJlAbk0JrZhVYMUZFmMocX4ZRYSf00J
ytDvTINcus52lZlZHltsJwMmvxAJc97UnUi9LMP5KlO94JrfUqHs9PX00GoH8ohJ
BBgRAgAJBQJKHR9OAhsMAAoJEEl1LNCYSb4gGZcAn0lNalKWZGSZfZjHrqPYJqKK
IBG/AJ9rr/f+ulpVCgR5bk1UH9uMDidtwA==
=gpGC
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        *)
            die "Εσφαλμένο αποθετήριο: $repo"
            ;;
    esac

    if [ -z "$lines" ]; then
        lines="deb http://ppa.launchpad.net/$repo/ubuntu $release main
#deb-src http://ppa.launchpad.net/$repo/ubuntu $release main"
    fi
    if [ -z "$filename" ]; then
        filename="$(echo "$repo" | tr './' '_-')-$release.list"
    fi
    filename="/etc/apt/sources.list.d/$filename"

    bold "Γίνεται προσθήκη του αποθετηρίου $repo στις πηγές σας."
    echo "$lines" > "$filename"
    # apt-key add echoes an "OK", so produce similar output.
    echo "OK"
    bold "Γίνεται προσθήκη του δημοσίου κλειδιού του αποθετηρίου ώστε να θεωρείται αξιόπιστο."
    echo "$key" | apt-key add -
}


install_sch_scripts() {
    local repo release

    if [ "$(id -u)" -ne 0 ]; then
        bold "Για να γίνει προσθήκη αποθετηρίων απαιτούνται δικαιώματα διαχειριστή.
Θα χρειαστεί να εισάγετε τον κωδικό πρόσβασης του λογαριασμού σας."
        exec sudo sh "$0"
    fi

    release=$(lsb_release -sc)
    # Transform linuxmint names to respective ubuntu names
    if [ -f "/usr/share/mintsources/$release/mintsources.conf" ]; then
        release=$(sed -n 's/^base_codename=//p' "/usr/share/mintsources/$release/mintsources.conf")
    fi
    if [ "$release" != "precise" ] && [ "$release" != "trusty" ] &&
        [ "$release" != "wily" ] && [ "$release" != "xenial" ]
    then
        die "Τα sch-scripts μπορούν να εγκατασταθούν μόνο σε LTS εκδόσεις του Ubuntu."
    fi
    # Remove the old repository filenames that contain "." instead of "_".
    rm -f /etc/apt/sources.list.d/ts.sch.gr*.list
    add_repository "ts.sch.gr"
    add_repository "ts.sch.gr/repo"

    bold "Γίνεται ενημέρωση των διαθέσιμων πακέτων."
    apt-get -q update || die "Σφάλμα κατά την ενημέρωση των διαθέσιμων πακέτων."

    # Hide the nbd-client debconf dialog
    echo 'nbd-client	nbd-client/killall	boolean	false' | debconf-set-selections

    bold "Γίνεται εγκατάσταση των sch-scripts."
    apt-get --yes install sch-scripts || die "Σφάλμα κατά την εγκατάσταση των sch-scripts."

    bold "Γίνεται εκτέλεση των sch-scripts."
    sch-scripts >/dev/null 2>&1 &

    if [ -x "/usr/sbin/update-apt-xapian-index" ]; then
        bold "Γίνεται ενημέρωση του ευρετηρίου πακέτων."
        if ! update-apt-xapian-index; then
            die "Σφάλμα κατά την ενημέρωση του ευρετηρίου πακέτων."
        fi
    fi

    if [ -x /usr/bin/software-center ]; then
        bold "Μπορείτε πλέον να εγκαταστήσετε όποια πακέτα λογισμικού θέλετε από το Κέντρο Λογισμικού Ubuntu."
    else
        bold "Μπορείτε πλέον να εγκαταστήσετε όποια πακέτα λογισμικού θέλετε."
    fi
}

# First check if we need to spawn an x-terminal-emulator
if [ "$SPAWNED_TERM" != true ] && { [ ! -t 0 ] || [ ! -t 1 ] ;} &&
    xmodmap -n >/dev/null 2>&1
then
    title=${1##*/}
    case "$title" in
        -s|--source) title=${2##*/} ;;
        '') title=${0##*/} ;;
    esac
    SPAWNED_TERM=true exec x-terminal-emulator -T "$title" -e sh "$0" "$@"
fi

set -e
# Analyze the command line, set "$title" for exit messages, and run the command
case "$1" in
    -s|--source)
        script="$2"
        shift 2
        test -f "$script" || die "Script not found: $script"
        title=${script##*/}
        bold "Γίνεται εκτέλεση της εντολής: $title $*"
        . "$script"
        ;;
    '')
        # Special case: if run as /tmp/sch-scripts, install sch-scripts!
        if [ "${0##*/}" = "sch-scripts" ] && [ "$(pwd)" = "/tmp" ]; then
            title="sch-scripts"
            install_sch_scripts
            pause_exit $?
        else
            usage >&2
            pause_exit 1
        fi
        ;;
    *)
        # If we didn't spawn a terminal, just exec the command
        test "$SPAWNED_TERM" != true && exec "$@"
        title=${1##*/}
        bold "Γίνεται εκτέλεση της εντολής: $*"
        "$@"
        ;;
esac
ret=$?
if [ $ret -eq 0 ]; then
    bold "
Η εντολή '$title' ολοκληρώθηκε με επιτυχία."
else
    bold "
Η εντολή '$title' απέτυχε με κωδικό σφάλματος $ret."
fi
pause_exit $?
