#!/bin/sh
# Πρόγραμμα εγκατάστασης των sch-scripts.
# Copyright (c) 2009-2012 Alkis Georgopoulos <http://alkisg.mysch.gr>
# Για να εκτελέσετε το πρόγραμμα, πατήστε Alt+F2 για να εμφανιστεί ο διάλογος
# εκτέλεσης εφαρμογής, και επικολήστε την παρακάτω εντολή:
#   sh -c 'cd /tmp && wget ts.sch.gr/repo/sch-scripts && sh sch-scripts'

set -- ts.sch.gr ts.sch.gr/repo

usage()
{
    cat <<EOF
Χρήση: $0 <αποθετήριο>
Το <αποθετήριο> μπορεί να είναι ένα από τα παρακάτω:
  ts.sch.gr/repo     Αποθετήριο εκπαιδευτικού λογισμικού της Τεχνικής Στήριξης
  ts.sch.gr          Αποθετήριο ανοικτού λογισμικού της Τεχνικής Στήριξης
  ts.sch.gr/proposed Αποθετήριο ελέγχου ενημερώσεων της Τεχνικής Στήριξης
  epoptes            Αποθετήριο του λογισμικού διαχείρισης τάξης Επόπτης
  medibuntu          Αποθετήριο medibuntu για googleearth, skype κτλ
EOF
}

pause_on_exit()
{
    local pause

    if [ -n "$PAUSE_ON_EXIT" ]; then
        read -p "
Πατήστε [Enter] για να κλείσει το παρόν παράθυρο." pause
    fi
}

bold()
{
    if [ -z "$bold_first_time" ]; then
        bold_first_time=false
        bold_face=$(tput bold 2>/dev/null) || true
        normal_face=$(tput sgr0 2>/dev/null) || true
    fi
    echo "${bold_face}$@${normal_face}"
}    

warn()
{
    echo "$@" >&2
}

die()
{
    warn "$@"
    pause_on_exit
    exit 1
}

in_path()
{
    which "$@" >/dev/null 2>&1
}

check_release()
{
    local release

    release=$(lsb_release -sc)
    case "$release" in
        precise)
            RELEASE="$release"
            ;;
        wheezy)
            RELEASE="precise"
            ;;
        *)
            die "Τα sch-scripts μπορούν να εγκατασταθούν μόνο σε Ubuntu 12.04 (Precise).
Εσείς έχετε έκδοση: $release."
            ;;
    esac
}

repo_params()
# To get the parameters:
# apt-key list
# apt-key export 03AFA832
{
    local repo

    repo="$1"
    unset LINES FILENAME KEY
    case "$repo" in
        "medibuntu")
            LINES="## Please report any bug on https://bugs.launchpad.net/medibuntu/
deb http://packages.medibuntu.org/ $RELEASE free non-free
#deb-src http://packages.medibuntu.org/ $RELEASE free non-free"
            FILENAME="medibuntu.list" # The medibuntu site mentions this filename
            # Key id: 0C5A2783
            KEY='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEVmMkERBACje575/Xw5hwzqCcdaf4LgQdPLpTbZLNaVdcGd+D0nskBlQ8VA
tuJngq184aeFjD/XmlosfvidFgSc6w4/LRP/XUtyYcWIUk65tStPK0fggdDIVjC/
SsOY5V+a02+ypSZjxPOQSqG4Lxhs240S6O6tS3CKr/08s6lgD0UEa2Ay6wCgnyEF
zOBXTCwSDXtPUFYXS6pCUDED/3wED5EksgizUCLmz5MNSsKTFUZyxkA65vIs2IoP
RtiWG28TWiOU3N5hrVxQI531sTTOZE97KhHAfSfQajRlQ/1O69RNvRR4pNd3/WKD
OEMlmP6Ow0DV0CPCfOeKiIKvdCY4+278b7LcLXNIwQlG3bBzV/9i5hGTo8nZf8qj
pSxkA/0UIrBUWKhTpx3/VNq9oSFpXBbiB5/6CDGIl0pSptAuKE3I1Xii0dOXyuvS
uqtmWgDBz/12MEqzBt+V+FGvv+oCvO7M2f3nsnFrdbn66Gnsto3xs+6X+9M+vOXz
GH5l7Mbo+M4z84lAZdcKeHC1Mm7b52K5Vj15/CUXr/wFuwVSubQ0TWVkaWJ1bnR1
IFBhY2thZ2luZyBUZWFtIDxhZG1pbkBsaXN0cy5tZWRpYnVudHUub3JnPohjBBMR
AgAjAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AFAkZq3JoCGQEACgkQLrwmtgxa
J4Nj0gCfQ9dKbsuC+D/76ABbl5S/ROgF3HEAoJfSmeUdH/s/DFWiHS54gT3xgcQ0
iEYEEBECAAYFAkcCix4ACgkQRaA1e1F5WRDw2wCgsImq4rf5CDxIrMHFK+uNRGY/
mWUAn1xxs9so3+NjwM3lqDiQBg/niVfViEYEEBECAAYFAkdQEPsACgkQ5ZcsNbsK
EqwLxgCeP7ZTmgf2DqkLhD4jJ0LyvqhrhcwAn2ukS0ayUIniwImCkVVcZBMG/1cI
iEYEEBECAAYFAkfakPcACgkQqS/wkKFyAU4bPQCgkZsQG5zTUcnx9eGDqlrhLF83
rfUAnRGenWvCBe2gLJv8vn8PWEG9x0xntCpUaGUgTWVkaWJ1bnR1IFRlYW0gPG1l
ZGlidW50dUBzb3Mtc3RzLmNvbT6IYAQTEQIAIAUCRWYyQQIbAwYLCQgHAwIEFQII
AwQWAgMBAh4BAheAAAoJEC68JrYMWieDIDkAnia/B7Byh+giE1pzYCWdhfHUf5eT
AJwM/DtStYLcPUD1/dxOTZGNerRwY7kCDQRFZjJfEAgA1iWJ0rqXioomH+GllyzQ
FDek396dsKxQYi08X+/sYY4ZJ1KE0PEH8JwZi+dKM0ZpA+/7sXetVYlq8rqRyu/y
f4DZdWCMjsB5krXGOgCv51prb8Qo+vMGSWQ+oHleblS5zkAuAUY487bljSvcdrtg
5ITX3UGFgZnMLDO4cfmz8KHwpRlmxKy9tcGqnuK7f9i/A4VYGRJco/XL0vqyzhJp
BiT0jYIjkz2JwExnw6K7hyvyShK7vOsAz5g8IKLibVpJFyO4gRkcjz9B+DNJxeys
y7TVR5yDZIP8VcPe7hdJmdltBnC2Q9DbsUmI8oVWooZZQPTAX+/XyrXMSj0HEzAI
RwADBQf/cfDOSifYN7ZYqk5ZLnFN/AZc72eVjJD0xA7fKrkZ6glXNqXfjr7Mxfmq
EymsfNr09RANtSGdBLeAFxeE1Sldsq6pE58HxWp82RI8XgeCjzVlDOVzT63ck+U2
Dh0M7SvIiOP0OUTxgxpujeRLInnFLd9mNwfFufMlC3NI/VomN8NdIqU7LDuM9xAp
Q+nTnCOMy8pwqr8mIfc5UUKWAxxguvFnqY9AiQpGNHhpUebzRehxbEOBL7NEDF94
SXI+NGOxz66Uq52UOZES3bBEoLv2s2hq36boErWbmOmTd1OtxwwjMbqBRCVdIc9Q
oeNZyZ465e00wx2FZb94LmBCLyxqkYhJBBgRAgAJBQJFZjJfAhsMAAoJEC68JrYM
WieDhlsAoIFA0h9GaVOgVLQFFw1c4K1WRGgpAJ43cEsGcAqOxNYcJmo1QWX7jG6E
MQ==
=7mIX
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        "epoptes"|"epoptes/ppa")
            repo="epoptes/ppa"
            # Key id: 0350B375
            KEY='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.11 (GNU/Linux)

mI0ETox6kAEEALjfWJQ5WrMKt3tlICHPx2RKy+6RG0cG3y6og/yzPoBaclu6qeG6
O+bhgVmAJF/VP2im/rDnpQUclD8WimhQpjOm4veXFteIlGxPh6kS4Unr8IV2RYz9
4h/uzsuQ3/w7mEEls/9R8ayPagqYlapDCUlSBXVJ5n/wJBTdP0JmfHcdABEBAAG0
JExhdW5jaHBhZCBQUEEgZm9yIEVwb3B0ZXMgRGV2ZWxvcGVyc4i4BBMBAgAiBQJO
jHqQAhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBJ8myzA1CzdepGA/sF
CpcuGL67iF4hLHV2wMKGdfwHwtJ0+hzDc11JTYDsBhL943iI92pKX8ZE73eSkzOV
9l82t/swyHRSBFvGuGob4PbJVpgOsciERCNqiJd4Ps9PYElbP7Sv8qgrEuZTVb5D
UQEjWXxo66hl9QI64QXglRiPAbQwyZ0tYdFGkKZ0LA==
=8QRo
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        "ts.sch.gr"|"ts.sch.gr/ppa"|"ts.sch.gr/proposed")
            if [ "$repo" = "ts.sch.gr" ]
            then
                repo="ts.sch.gr/ppa"
            fi
            # Key id: 03AFA832
            KEY='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mI0ESh2aVQEEALM30nllN7ZvEY7lfOTYoamJWl3axh5h0g4xZB7AXKop1/7zq3uf
uGITGBZuY+YTnn3WhUp76aQzgAkfsMfqyeIrPZVDpY+YMLng2WN4Q9NkziR0gfmI
vOZk157/ug20KRSAmyQnmmKKs1O3qc1ATxJPVvu/OojS6E6DKdHALMhPABEBAAG0
EkxhdW5jaHBhZCBUZXN0IFBQQYifBDABAgAJBQJKLLIAAh0gAAoJEDxyYHsDr6gy
b98EAJU7qCuq7znpT1dbNOYwbjPqBry6MOzhMXIl6RnFGQkgTPi2pLQbJq0U/v46
uGbqPx0o8qFTC/Tg8RRJPH6Xqe7kl7gkfpA/cCCSIEQtnrd8EzOYHGMrt+1FtMsZ
0rfyqQL8Ix7K566dpgEVdfouQJSGIUFZzcd8TsDSrlCHlHM9iLYEEwECACAFAkod
mlUCGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRA8cmB7A6+oMvSKA/9zDRHJ
gInCDBhcmgPBqgDc1Fvcf9z2bcNnL26Af3E8/629vDG2YRU1XtNc9WnYpUgZpDPH
LWbD/zoZuXgKwE1yjPQLJMS153zAG0bsmAaWegHEyQNag7KvWIplyq/I0mac9Q+Z
NmAAta8KJ2tQahnqv4/k7Mlm5jurdoX0fEhPBbRDzpHPgM6/zrjOtc+Ezq7Pgc65
zr8gzqTOtc+Hzr3Ouc66zq7PgiDOo8+Ezq7Pgc65zr7Ot8+CIM6jzpXOoM6VzpfO
pYi2BBMBAgAgBQJKLLHeAhsDBgsJCAcDAgQVAggDBBYCAwECHgECF4AACgkQPHJg
ewOvqDJUBwQAi0TayFknNG4oP7RFS27ktB4O12uB4ePqwkfwr2bWW6sAlUvObvKV
b2tjo9LumXWjssFmhYQlf4XlMab/GZno/hwIihH21bl4D/qCOmIvAEbim5rwOYHl
lggdYwVk8U8LiO9Ime8BxgehvRle69qr4KLuSln29jYCscD2PLGbGsqIuQQTAQIA
IwIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheABQJKLLNkAhkBAAoJEDxyYHsDr6gy
yM8D/jvaXRV0iOlU5c6kbUKMHzmEWM59QYO+dgzSaDmx77svICb2dcrY+onYpNOB
0ZHmcwlyc4hUw/b7l5t9emRns7lUgw/BBaDnk3vsqWQIyeIcuXZV5JAtwCVBZsE7
NPBKU1xbjWICQVXVB3ZEkIi2Y6tHzVx5hX1GqiRxVfZXo4N/
=buPk
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        "ts.sch.gr-repo"|"ts.sch.gr/repo")
            repo="ts.sch.gr/repo"
            LINES="deb http://ts.sch.gr/repo stable main"
            # Key id: 9849BE20
            KEY='-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEodH04RBAC8Gnx7SOytmQCLkvelxjCMOLxDSaaJiGaq3bJBTUJlBaAf3cqb
SBW4bfp9DQkgKHcnsIrGC+zUxYEzZrc6ZvEz+i+v1iMHo+QpJWAJLZ7CF8SRfvTb
w/zysKxSkn59CRfM2gZuoSfVXYKWw9v7kmriKZ7P5ybbssunq76reaWb4wCgmflB
h/vgoQCj5Z5Deu6HQwEn+0sD/0xZvqYGtzHXDEAz2BBXJtORkyS5R6y8KRqgAcQ/
wDtV1xnG52/gOZH6maauqKVpH5S66EFgxr+Rl0IEOCQFbHLUtGZl4dPI/kFD6AcI
JPGKQXgiIwP9yrYJbTnl9tLIPo3Dgv0cfmj4gg/aibjwWPtNTJYckOPSQyVnUEg6
rAJgBAC8AgS2vsau3xPPqRXybdHKqc0+xjZx2NW6xVYGF825UHdx1yaZjgHcw9G1
YfqVoS1eOScXrC6T+BC84fYYT8/a4dS7X2Rk74FYKwcmJ/QW+8a56f1b6K1DcSy8
godpz3e1LkyIL6/58k7qM5M7dJ+lms9wirmq30lkYkWnWbD/QrRlSGVsbGVuaWMg
U2Nob29scyBUZWNobmljYWwgU3VwcG9ydCBUZWFtICjOpM61z4fOvc65zrrOriDO
o8+Ezq7Pgc65zr7OtyDOo86VzqDOlc6XzqUpIDxkZXZzQHRzLnNjaC5ncj6IYAQT
EQIAIAUCSh0fTgIbAwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEEl1LNCYSb4g
058AniBnHSKSZk22AaHmBthl9mwZaXP9AJ4yTfMDHC/itOv0hJLUIDnGnndwxbkC
DQRKHR9OEAgA7CtHQByegpJpRJunBSvqu8xtz/buXVhWBiPpYNBqQF5S4OGXngru
zKlcgzYt5sK8ve4022ba5NfKUEOgQiTSP3p/9w9JYxrL30IeeHKPwL3NLeS3DNV8
wxVJB4CXYHmOQ9B0RM4nBj3wOFEv1UiPMC7kox+E9bi9lQJXVmECqKrtadvwaoqU
ncvhMb/Etg3Kstrsi7MkPtCalbgCi/acvDSKF1Wf6EKFla7eywY6U2heFASUpMg4
2FqA4DyL/avg5zvdDg6cuk05P4Zudq/e80hyvVWA6LPWM5FEJnPlz31vWKMKtrRH
pUEFFBiOzb2FQg9zyRlkF8qjPCEkKnC+twAECwgAmiVlyqSpl7K+y2/yZB4dWCjE
AyHJRUK8AVL0KGPgTo+YWnBImq+7eOw0hVMVbMWrwv2r0s/l7SsBI723KsMVvurY
A2/kqj8+UM24t40YDAr8qAeP4UACtWlRy9PAUQQ1+4ygPYnRK81RBXLL2WYF25GL
Qj+4zvUz4bqkQTv91fjjwpX03YaoVaBKngNjPOgOlQtZM0E5k7C98pESOb4AHoju
y2tMEfhoa2cf7KdywmN0EjYHaL+3VIb6mTJlAbk0JrZhVYMUZFmMocX4ZRYSf00J
ytDvTINcus52lZlZHltsJwMmvxAJc97UnUi9LMP5KlO94JrfUqHs9PX00GoH8ohJ
BBgRAgAJBQJKHR9OAhsMAAoJEEl1LNCYSb4gGZcAn0lNalKWZGSZfZjHrqPYJqKK
IBG/AJ9rr/f+ulpVCgR5bk1UH9uMDidtwA==
=gpGC
-----END PGP PUBLIC KEY BLOCK-----'
            ;;

        *)
            die "$(usage)"
            ;;
    esac

    if [ -z "$LINES" ]; then
        LINES="deb http://ppa.launchpad.net/$repo/ubuntu $RELEASE main
#deb-src http://ppa.launchpad.net/$repo/ubuntu $RELEASE main"
    fi
    if [ -z "$FILENAME" ]; then
        FILENAME="$(echo "$repo" | tr '/' '-')-$RELEASE.list"
    fi
    FILENAME="/etc/apt/sources.list.d/$FILENAME"
}

# Main
FULLNAME="$(cd $(dirname "$0") && pwd)/$(basename "$0")"
if [ ! -t 0 ]  # if stdin is not a terminal, e.g. if ran with Alt+F2
then
    PAUSE_ON_EXIT=true exec xterm -title "Προσθήκη αποθετηρίου $*" -e \
        /bin/sh "$FULLNAME" "$@"
fi
test "$#" -eq 0 && die "$(usage)"
if [ "$(id -u)" -ne 0 ]; then
    bold "Για να γίνει προσθήκη αποθετηρίων απαιτούνται δικαιώματα διαχειριστή.
Θα χρειαστεί να εισάγετε τον κωδικό πρόσβασης του λογαριασμού σας."
    exec sudo "PAUSE_ON_EXIT=$PAUSE_ON_EXIT" /bin/sh "$FULLNAME" "$@"
fi

check_release
for repo in "$@"; do
    repo_params "$repo" "$release"

    bold "Γίνεται προσθήκη του αποθετηρίου $repo στις πηγές σας."
    echo "$LINES" > "$FILENAME"
    # apt-key add echoes an "OK", so produce similar output.
    echo "OK"
    bold "Γίνεται προσθήκη του δημοσίου κλειδιού του αποθετηρίου ώστε να θεωρείται αξιόπιστο."
    echo "$KEY" | apt-key add -
done

bold "Γίνεται ενημέρωση των διαθέσιμων πακέτων."
apt-get -q update || die "Σφάλμα κατά την ενημέρωση των διαθέσιμων πακέτων."

bold "Γίνεται εγκατάσταση των sch-scripts."
apt-get --yes install sch-scripts || die "Σφάλμα κατά την εγκατάσταση των sch-scripts."

bold "Γίνεται εκτέλεση των sch-scripts."
sch-scripts >/dev/null 2>&1 &

bold "Γίνεται ενημέρωση του ευρετηρίου πακέτων."
if in_path "update-apt-xapian-index"; then
    if ! update-apt-xapian-index; then
        die "Σφάλμα κατά την ενημέρωση του ευρετηρίου πακέτων."
    fi
fi

if [ "$#" -eq 1 ]; then
    bold "Το αποθετήριο $* προστέθηκε στις πηγές σας."
else
    bold "Τα αποθετήρια $* προστέθηκαν στις πηγές σας."
fi

if in_path "software-center"; then
    bold "Μπορείτε πλέον να εγκαταστήσετε όποια πακέτα λογισμικού θέλετε από το Κέντρο Λογισμικού Ubuntu."
fi
pause_on_exit
